version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitsa
      RABBITMQ_DEFAULT_PASS: mypa55w0rd!
    ports:
      - "5672:5672"
      - "15672:15672"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1414:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: superPuperPassword!15641
  web:
    image: back
    depends_on:
      - mssql
      - rabbitmq
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4040:443"
    environment:
      MessageBroker__Username: rabbitsa
      MessageBroker__Password: mypa55w0rd!
      MessageBroker__Hostname: rabbitmq
      MessageBroker__Port: 5672
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: $CREDENTIAL_PLACEHOLDER$
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__BeaverTinderDatabase: Data Source=mssql;Initial Catalog=BeaverTinderDatabase;User=sa;Password=superPuperPassword!15641;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
    volumes:
      - ~/.aspnet/https:/https:ro
  supportconsumer:
    image: support-consumer
    depends_on:
      - mssql
      - rabbitmq
    build:
      context: ./
      dockerfile: DockerfileConsumer
    ports:
      - "4041:443"
    environment:
      MessageBroker__Username: rabbitsa
      MessageBroker__Password: mypa55w0rd!
      MessageBroker__Hostname: rabbitmq
      MessageBroker__Port: 5672
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: $CREDENTIAL_PLACEHOLDER$
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__BeaverTinderDatabase: Data Source=mssql;Initial Catalog=BeaverTinderDatabase;User=sa;Password=superPuperPassword!15641;Connect Timeout=300;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
    volumes:
      - ~/.aspnet/https:/https:ro
  react:
    image: front
    build:
      context: /front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"