apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: andrewkhoryakov/beaver-tinder-web
        env:
          - name: MessageBroker__Username
            value: rabbitsa
          - name: MessageBroker__Password
            value: mypa55w0rd!
          - name: MessageBroker__Hostname
            value: rabbitmq-balancer
          - name: MessageBroker__Port
            value: "5672"
          - name: ConnectionStrings__BeaverTinderDatabase
            value: Data Source=mssql-balancer,1433;Initial Catalog=BeaverTinderDatabase;User=sa;Password=superPuperPassword!15641;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;MultipleActiveResultSets=true;
        ports:
          - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: web-balancer
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 80
  

