FROM node:current-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build
# Запускаем анализатор кода Sonar
RUN sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.sources=./src -Dsonar.host.url=http://your_sonarqube_url -Dsonar.login=your_sonarqube_token

# Запускаем приложение
EXPOSE 3000
CMD ["npm", "start"]
