# Используем базовый образ Node.js
FROM node:latest

# Установка рабочей директории внутри контейнера
WORKDIR /app

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование всех файлов проекта внутрь контейнера
COPY . .

# Сборка приложения
RUN npm run build

# Указание порта, который будет использоваться при запуске контейнера
EXPOSE 3000

# Команда для запуска приложения
CMD ["npm", "start"]